package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Junx27/junxzy/internal/ui"
)

type InitCommand struct{}

func (i InitCommand) Name() string {
	return "init"
}

func (i InitCommand) Execute(args []string) {
	if len(args) < 1 {
		ui.StopError("Nama project wajib diisi")
		return
	}

	projectName := args[0]

	if _, err := os.Stat(projectName); !os.IsNotExist(err) {
		ui.StopError("Project sudah ada: " + projectName)
		return
	}

	ui.Start("Membuat folder project...")
	createDir(projectName)
	ui.StopSuccess("Folder project dibuat")

	base := projectName

	services := []string{"user", "auth", "product"}

	ui.Start("Membuat services...")
	for _, svc := range services {
		createService(base, svc)
	}
	ui.StopSuccess("Semua services berhasil dibuat")

	ui.Start("Membuat gateway...")
	os.MkdirAll(filepath.Join(base, "gateway"), os.ModePerm)
	ui.StopSuccess("Gateway dibuat")

	ui.Start("Membuat docker-compose...")
	createDockerCompose(base)
	ui.StopSuccess("docker-compose dibuat")

	ui.Start("Membuat README...")
	createReadme(base, projectName)
	ui.StopSuccess("README dibuat")

	fmt.Println()
	ui.Success("Project microservices berhasil dibuat: " + projectName)
}

// ================= HELPER =================

func createDir(path string) {
	os.MkdirAll(path, os.ModePerm)
}

func createService(base, name string) {
	servicePath := filepath.Join(base, "services", name)

	dirs := []string{
		"handler",
		"service",
		"repository",
	}

	for _, d := range dirs {
		os.MkdirAll(filepath.Join(servicePath, d), os.ModePerm)
	}

	// main.go sederhana
	mainFile := `package main

import "fmt"

func main() {
	fmt.Println("` + name + ` service running")
}
`

	os.WriteFile(filepath.Join(servicePath, "main.go"), []byte(mainFile), os.ModePerm)
}

func createDockerCompose(base string) {
	content := `version: '3'

services:
  user:
    build: ./services/user
    ports:
      - "8001:8000"

  auth:
    build: ./services/auth
    ports:
      - "8002:8000"

  product:
    build: ./services/product
    ports:
      - "8003:8000"
`

	os.WriteFile(filepath.Join(base, "docker-compose.yml"), []byte(content), os.ModePerm)
}

func createReadme(base, name string) {
	content := "# " + name + `

Microservices project generated by Junxzy CLI 🚀
`

	os.WriteFile(filepath.Join(base, "README.md"), []byte(content), os.ModePerm)
}
